[package]
name = "rift-client"
version = "0.1.0"
edition = "2024"
description = "Rust client for Rift's Mach IPC API"
license = "Apache-2.0"

[dependencies]
serde = "1.0.201"
serde_json = "1.0.145"
rift-protocol = { path = "../rift-protocol" }
thiserror = "2.0.17"

[dev-dependencies]
ctrlc = "3.5.2"
