{ lib }:

attrs:
let
  escapeString = s:
    builtins.replaceStrings
      [ "\\" "\"" "\n" "\t" "\r" ]
      [ "\\\\" "\\\"" "\\n" "\\t" "\\r" ]
      s;

  toTOMLValue = value:
    if builtins.isBool value then
      (if value then "true" else "false")
    else if builtins.isInt value || builtins.isFloat value then
      builtins.toString value
    else if builtins.isString value then
      "\"" + (escapeString value) + "\""
    else if builtins.isList value then
      "[" + (builtins.concatStringsSep ", " (map toTOMLValue value)) + "]"
    else if builtins.isAttrs value then
      "{" + (builtins.concatStringsSep ", " (lib.mapAttrsToList (k: v: k + " = " + (toTOMLValue v)) value)) + "}"
    else
      throw "Unsupported TOML value type: ${builtins.typeOf value}";

  sectionHeader = path:
    if builtins.length path == 0 then ""
    else "[" + (builtins.concatStringsSep "." path) + "]";

  isSimple = v:
    if builtins.isAttrs v then false
    else if builtins.isList v && builtins.length v > 0 then
      !(builtins.isAttrs (builtins.elemAt v 0))
    else true;

  keyValuePairs = indent: attrset:
    let
      simpleItems = lib.filterAttrs (k: v: isSimple v) attrset;
      lines = lib.mapAttrsToList (k: v: indent + k + " = " + (toTOMLValue v)) simpleItems;
    in builtins.concatStringsSep "\n" lines;

  nestedSections = path: indent: attrset:
    let
      complexItems = lib.filterAttrs (k: v: !isSimple v) attrset;
      processItem = k: v:
        if builtins.isAttrs v then
          toTOMLSection (path ++ [k]) v
        else if builtins.isList v && builtins.length v > 0 && builtins.isAttrs (builtins.elemAt v 0) then
          let
            tableLines = map (item:
              let
                header = "[[" + (builtins.concatStringsSep "." (path ++ [k])) + "]]";
                pairs = keyValuePairs "" item;
                nested = nestedSections (path ++ [k]) "" item;
                newline = builtins.fromJSON ''"\n"'';
              in if pairs != "" then header + newline + pairs + (if nested != "" then newline + nested else "")
                 else if nested != "" then header + newline + nested
                 else header
            ) v;
          in builtins.concatStringsSep "\n\n" tableLines
        else "";
    in builtins.concatStringsSep "\n" (lib.mapAttrsToList processItem complexItems);

  toTOMLSection = path: attrset:
    let
      header = sectionHeader path;
      indent = "  ";
      pairs = keyValuePairs indent attrset;
      nested = nestedSections path indent attrset;
      newline = builtins.fromJSON ''"\n"'';
      result = if header == "" then
        (if pairs != "" then pairs else "")
        + (if nested != "" then (if pairs != "" then newline else "") + nested else "")
      else
        header + (if pairs != "" then newline + pairs else "")
        + (if nested != "" then newline + newline + nested else "");
    in result;

  rootPairs = keyValuePairs "" attrs;
  rootSections = nestedSections [] "" attrs;
  content = if rootPairs != "" then rootPairs + (if rootSections != "" then "\n\n" + rootSections else "")
            else rootSections;
in "# Generated by Nix\n\n" + content + "\n"
